spring:
  application:
    name: sprint
  datasource:
    url: ${DB_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: false
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  token:
    access-expiration-time: ${ACCESS_EXPIRATION_TIME}
    refresh-expiration-time: ${REFRESH_EXPIRATION_TIME}
